# Generated by Django 2.1 on 2018-08-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.PositiveIntegerField()),
                ('pos_y', models.PositiveIntegerField()),
                ('value', models.SmallIntegerField(choices=[(1, 'POS'), (-1, 'NEG'), (0, 'NEU')], default=0)),
            ],
            options={
                'db_table': 'annotation',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('ready', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['pos_x'], name='annotation_pos_x_4f228c_idx'),
        ),
    ]
