# Generated by Django 2.0.7 on 2018-09-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['ready'], name='document_ready_ec1293_idx'),
        ),
    ]
